services:
  - type: web
    name: edilpro-backend
    env: node
    buildCommand: |
      cd backend
      npm install
      npm install -g nodemon
    startCommand: cd backend && nodemon server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 